project:
  title:        "FSM Gearbox Controller"
  author:       "MoisesPabloc"
  discord:      ""
  description:  "Caja de cambios automática FSM con salida a 7 segmentos"
  language:     "Verilog"
  clock_hz:     0
  tiles: "1x1"
  top_module:  "tt_um_MoisesPabloc"
  source_files:
    - "cloc_devider.v"
    - "gearbox_fsm.v"
    - "top_gearbox_fsm.v"

pinout:
  ui[0]: "reset"
  ui[1]: "shift_up"
  ui[2]: "shift_down"
  ui[3]: "brake"
  ui[4]: ""
  ui[5]: ""
  ui[6]: ""
  ui[7]: ""
  uo[0]: "SEG_A"
  uo[1]: "SEG_B"
  uo[2]: "SEG_C"
  uo[3]: "SEG_D"
  uo[4]: "SEG_E"
  uo[5]: "SEG_F"
  uo[6]: "SEG_G"
  uo[7]: ""
  uio[0]: ""
  uio[1]: ""
  uio[2]: ""
  uio[3]: ""
  uio[4]: ""
  uio[5]: ""
  uio[6]: ""
  uio[7]: ""
